# Generated by Django 5.2.7 on 2025-10-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_precios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglaprecio',
            name='aplica_articulo',
            field=models.ForeignKey(blank=True, help_text='Si se define, esta regla solo aplica a este artículo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_precios.articulo'),
        ),
        migrations.AddField(
            model_name='reglaprecio',
            name='aplica_grupo',
            field=models.ForeignKey(blank=True, help_text='Si se define, esta regla aplica a cualquier artículo de este grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_precios.grupoarticulo'),
        ),
        migrations.AddField(
            model_name='reglaprecio',
            name='aplica_linea',
            field=models.ForeignKey(blank=True, help_text='Si se define, esta regla aplica a cualquier artículo de esta línea.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_precios.lineaarticulo'),
        ),
        migrations.CreateModel(
            name='CombinacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('articulos', models.ManyToManyField(help_text='Artículos que forman parte de esta combinación.', related_name='combinaciones', to='gestion_precios.articulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='gestion_precios.listaprecio')),
            ],
        ),
        migrations.AddField(
            model_name='reglaprecio',
            name='aplica_combinacion',
            field=models.ForeignKey(blank=True, help_text='Si se define, esta regla aplica si la combinación de productos está presente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_precios.combinacionproducto'),
        ),
    ]
